# Generated by Django 5.1.5 on 2025-01-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_sittingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sittingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
