# Generated by Django 5.1.5 on 2025-04-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
