# Generated by Django 5.1.5 on 2025-04-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_sittingresponsemessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sittingresponsemessage',
            old_name='request',
            new_name='sitting_request',
        ),
    ]
