# Generated by Django 5.1.5 on 2025-06-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_rename_request_sittingresponsemessage_sitting_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sittingrequest',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sittingresponsemessage',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
