# Generated by Django 5.1.5 on 2025-02-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('posts', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sitting_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.sittingrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request', 'Sitting Request'), ('comment', 'Comment'), ('like', 'Like')], default='comment', max_length=20),
        ),
    ]
