# Generated by Django 5.1.5 on 2025-04-24 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_post'),
        ('profiles', '0004_alter_followrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request', 'Sitting Request'), ('comment', 'Comment'), ('like', 'Like'), ('follow', 'Follow')], default='comment', max_length=20),
        ),
    ]
